(*
**  Analog Circuit Design using Grammatical Evolution (ACID-GE)
**  Analog Circuit Design using Multigrammatical Evolution (ACID-MGE)
**
**  Copyright (c) 2021 Federico Castejon, Enrique J. Carmona
**
**  This program is free software: you can redistribute it and/or modify
**  it under the terms of the GNU General Public License as published by
**  the Free Software Foundation, either version 3 of the License, or
**  (at your option) any later version.
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU General Public License for more details.
**
**  You should have received a copy of the GNU General Public License
**  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*)
(*
 * MultiNetlistComunTop2.ebnf
 * 
 * 2a multigramática común para todas las gramáticas
 *)
 
LIST = <GEResult>;

RESISTORVAL = NONZERODIGIT, DECIMAL, DIGIT, EXP, DIGIT, SEP, DUMMY;

CAPACITORVAL = NONZERODIGIT, DECIMAL, DIGIT, EXP, EXPONENT, SEP, DUMMY;

(* 2N3904 es NPN y 2N3906 es PNP *)
BJTTYPE = TYPE, SEP, DUMMY, SEP, DUMMY, SEP, DUMMY;

TYPE = "Q2N3904" | "Q2N3906";

MOSTYPE = MODELNMOS | MODELPMOS;

MODELNMOS = '0', SEP, "NMOS1 L=10u W=";

MODELPMOS = '4', SEP, "PMOS1 L=10u W=";

CHANNELWIDTH = NONZERODIGIT, DIGIT, 'u' | '1', DIGIT, DIGIT, 'u';

DUMMY = "nulo1" | "nulo2"; 

(* equivalente con extensión
DIGIT = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
NONZERODIGIT = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
*)

DIGIT = <GECodonValue: 0, 9>;

NONZERODIGIT = <GECodonValue: 1, 9>;

(*
EXPONENT = <GECodonValue: -12, -3>;
*)

EXPONENT = "-12" | "-11" | "-10" | "-9" | "-8" | "-7" | "-6" | "-5" | "-4" | "-3";


EXP = "e";

DECIMAL = ".";

SEP = " ";

EOL = ?EOL?;

CR = ?Carriage return?;
